version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  web:
    build: .
    volumes:
      - ./log:/home/app/depot/log
    secrets:
      - source: master_key
        target: /home/app/depot/config/master.key
    environment:
      - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
    ports:
      - '3000:3000'
    depends_on:
      - db

secrets:
  master_key:
    file: ./config/master.key

volumes:
  pgdata:
